name: Deploy to GKE

on:
  push:
    branches:
    - main
    - master
  workflow_dispatch:


env:
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DEPLOYMENT_NAME: flask-app
  DOCKERHUB_USERNAME: ffiuca
  IMAGE_NAME: insigna-test

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$GITHUB_SHA \
          -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest \
          ./q1/project

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$GITHUB_SHA
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT_ID }}
        export_default_credentials: true

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

    - name: Deploy to GKE
      run: |
        kubectl apply -f ./k8s-deployment.yaml
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n insigna-flask
        kubectl get services -n insigna-flask -o wide
